IF DB_ID('CUPPO') IS NULL CREATE DATABASE [CUPPO];
GO
USE [CUPPO];
GO

IF SCHEMA_ID('Log') IS NULL EXEC('CREATE SCHEMA [Log]');
GO
IF SCHEMA_ID('Security') IS NULL EXEC('CREATE SCHEMA [Security]');
GO
